version: '2'

services:

  db:
    image: mysql:latest
    hostname: db
    container_name: db
    volumes:
    - ./db/conf.d:/etc/mysql/conf.d
    - ./db/data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=wtadmin2018
    networks:
      intern:
        ipv4_address: 10.20.30.25
    
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: leroy.ephec-ti.be
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - ./mail/maildata:/var/mail
    - ./mail/mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    networks:
      intern:
        ipv4_address: 10.20.30.75

  web:
    image: chris/web:latest
    container_name: web
    hostname: web
    volumes:
      - ./web/www:/var/www
      - ./web/etc:/etc/apache2
      - ./web/log:/var/log/apache2
      - ./web/ssl/:/etc/ssl
    networks:
      intern:
        ipv4_address: 10.20.30.50

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    hostname: reverse-proxy
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - ./reverse-proxy/etc:/etc/nginx
      - ./reverse-proxy/log:/var/log/nginx
      - ./reverse-proxy/www:/var/www
    networks:
      intern:
        ipv4_address: 10.20.30.100
        
networks:
  intern:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
          ip_range: 10.20.30.0/24
          gateway: 10.20.30.1
          
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

